filter:
	gcc -fsanitize=signed-integer-overflow -fsanitize=undefined -ggdb3 -O0 -Wunused-parameter -std=c11 -Wall -Werror -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wshadow -o filter filter.c helpers.c helpers.h bmp.h -lm
